### ISSUE TITLE
Set up redirects for the top 10 RubyForge projects

### ISSUE THREAD

**Issue by tomstuart** [tomstuart/rubyforge-redirects#2]
This involves:
- [ ] finding the 10 most “popular” (by downloads? by inbound link volume?) RubyForge-hosted projects
- [ ] finding where they’re hosted now (if anywhere)
- [ ] setting up redirects for them

**Comment by chrislo** [comment]
https://web.archive.org/web/20130122115131/http://rubyforge.org/top/toplist.php?type=downloads gives the most popular projects by downloads. The top dozen are:

```
http://rubyforge.org/projects/rubyinstaller/
http://rubyforge.org/projects/rubygems/
http://rubyforge.org/projects/rails/
http://rubyforge.org/projects/instantrails/
http://rubyforge.org/projects/redmine/
http://rubyforge.org/projects/rubot/
http://rubyforge.org/projects/flvtool2/
http://rubyforge.org/projects/railsinstaller/
http://rubyforge.org/projects/rmagick/
http://rubyforge.org/projects/emm-ruby/
http://rubyforge.org/projects/net-ssh/
http://rubyforge.org/projects/rake/
http://rubyforge.org/projects/phprpc/
http://rubyforge.org/projects/codeforpeople/
http://rubyforge.org/projects/sqlite-ruby/
http://rubyforge.org/projects/activesupport/
http://rubyforge.org/projects/seattlerb/
http://rubyforge.org/projects/activerecord/
http://rubyforge.org/projects/ruby-dbi/
http://rubyforge.org/projects/win32utils/
```

**Comment by tomstuart** [comment]
Thanks Chris! Is there any indication how many of these had project pages at `<projectname>.rubyforge.org`? I hadn’t thought of redirecting the `rubyforge.org/projects` pages, but maybe that’s worth doing too?

**Comment by chrislo** [comment]
I was trying to establish that by searching (in Google) for e.g. `rubyinstaller.rubyforge.org` - but no joy so far, I don't think the 'link:' syntax works as you previously noticed. I'm going to take a look at some older ruby books I have to see if there's any pattern! 

I think it might be worth redirecting `rubyforge.org/projects` pages too.

**Comment by lazyatom** [comment]
I've also been using this Google search through the text of a version of the "Ruby Cookbook": https://books.google.co.uk/books?id=bJkznhZBG6gC&pg=PA735&lpg=PA735&dq=rake.rubyforge.org&source=bl&ots=AmJ0i6pXUH&sig=CXvdLHaz3yNr57oXakMt6VKZfyQ&hl=en&sa=X&ei=e5ncVP3AO8bPaNrrgYAE&ved=0CFwQ6AEwCQ#v=onepage&q=rubyforge.org&f=false

**Comment by h-lame** [comment]
nokogiri certainly used to be nokogiri.rubyforge.org (https://www.google.co.uk/search?q=nokogiri+rubyforge&oq=nokogiri+rubyforge&aqs=chrome..69i57.4198j0j7&sourceid=chrome&es_sm=119&ie=UTF-8#q=%22nokogiri.rubyforge.org%22)

**Comment by h-lame** [comment]
Lots of older gems on rubygems.org still point their homepage etc.. at rubyforge.  I wonder if it is possible to get a complete dump of gemspecs from rubygems and do some automatic parsing / generation of redirects?

For example I was just looking at https://rubygems.org/gems/log4r and its homepage is listed as http://log4r.rubyforge.org/.

Doing:

``` terminal
$ gem specification log4r --remote
```

gives: 

``` yaml
--- !ruby/object:Gem::Specification
name: log4r
version: !ruby/object:Gem::Version
  version: 1.1.10
platform: ruby
authors:
- Colby Gutierrez-Kraybill
autorequire: 
bindir: bin
cert_chain: []
date: 2012-01-02 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: bundler
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.0.0
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.0.0
- !ruby/object:Gem::Dependency
  name: rake
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: 0.8.7
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: 0.8.7
description: 'See also: http://logging.apache.org/log4j'
email: colby@astro.berkeley.edu
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: http://log4r.rubyforge.org
licenses: []
metadata: 
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubyforge_project: 
rubygems_version: 2.2.2
signing_key: 
specification_version: 3
summary: Log4r, logging framework for ruby
test_files: []
```

Obviously you don't want to do this by hand, but maybe we could have a word with the rubygems folks to get the data in one go.
